name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  built: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Booooooora
        run: docker run -d --name=test-mysql -e MYSQL_ROOT_PASSWORD=’mypassword’
        
